### PR TITLE
Custom cache path

### PR DESCRIPTION
**Pull request by samizzo**
This PR adds a command-line argument to allow overriding the cache path. The path is also used for saving ini files (rather than using the script directory).

### CODE REVIEW

**Comment by sttz** [comment]
Maybe it would make sense to just have a `--data-dir` option that gets used for the cache, ini files and packages instead of having separate options for them?

On the upside, that would mean less options and make it simpler to bundle everything together for offline installation. On the other hand, is there a use case where you need to have the packages in a separate place than the cache and ini files?

**Comment by samizzo** [comment]
Yeah a `--data-dir` option for everything would make sense, or everything in the one place, just not in the location where the `install-unity` script is. I have `install-unity` checked into my project, and I run it as part of my build scripts on my build machine, and my build machine user is in `sudoers` so I can run via `sudo` without a password prompt. But when it runs it puts the ini and cache files in the current directory and owned by `root` which is problematic for my nightly clean process (which deletes everything and does a fresh checkout).

So I don't really need the packages in a different directory. I just want the ini and cache to **not** be saved into the script's directory. Maybe they could go into the `package-store` path along with the downloaded packages?

**Comment by sttz** [comment]
Ok, I used the opportunity to clean up a few other things regarding where and how files are stored as well in e8898962.

By default all files are now stored in `~/Library/Application Support/install-unity`, so the script dir doesn't get polluted by files anymore. `--package-store` is gone and instead there's `--data-dir` to put all files in a different directory. This also makes offline installation a bit easier, since everything is in one place.

Hope this helps!

**Comment by samizzo** [comment]
Thanks, that sounds great! I'll check it out!

**Pull request closed without merging**
